@startuml
'https://plantuml.com/class-diagram
|spring context|
start
|spring ext bean|
:实例化BeanFactoryPostProcessor实现类;
:执行BeanFactoryPostProcessor的postProcessBeanFactory方法;
:实例化BeanPostProcessor的postProcessBeforeInitialization方法;
:实例化InstantiationAwareBeanPostProcessorAdapter实现类;
:执行InstantiationAwareBeanPostProcessorAdapter的postProcessBeforeInstantiation方法;
|#AntiqueWhite|biz bean|
:执行Bean的构造器;
|spring ext bean|
:执行InstantiationAwareBeanPostProcessorAdapter的postProcessPropertyValues方法;
|#AntiqueWhite|biz bean|
:为bean注入属性;
:执行BeanNameAware的setBeanName方法;
:执行BeanFactoryAware的setBeanFactory方法;
|spring ext bean|
:执行BeanPostProcessor的postProcessBeforeInitialization方法;
|biz bean|
:执行BeanPostProcessor的postProcessAfterInitialization方法;
:执行InstantiationAwareBeanPostProcessorAdapter的postprocessAfterInitialization方法;
|spring context|
:容器初始化成功;
:开始销毁容器;
|spring ext bean|
|biz bean|
:执行DisposableBean的destroy方法;
:执行Bean的destroy-method属性指定的方法;
|spring ext bean|
|spring context|
stop
@enduml